In [12]:
# 基本. 主に誤差の話.

In [13]:
s = 0
for i in range(1000):
    s += 0.001
s

1.0000000000000007

In [18]:
"""
無限ループする
s = 0
while s != 1.:
    print(s)
    s += 0.1
"""

# 無限ループしない
eps = 1e-10
s = 0
while abs(s - 1.) > eps:
    print(s)
    s += 0.1

0
0.1
0.2
0.30000000000000004
0.4
0.5
0.6
0.7
0.7999999999999999
0.8999999999999999


In [19]:
import qeq

qeq.qeq(1, 5, 6)

(-2.0, -3.0)

In [20]:
qeq.qeq(1, 1.000000001, 0.000000001)

(-1.0000000272292198e-09, -1.0)

In [21]:
import numpy as np

def qeq2(a, b, c):
    alpha = (-b - np.sign(b) * np.sqrt(b**2 - 4 * a * c)) / (2 * a)
    beta = c / (a * alpha)
    return (alpha, beta)

In [22]:
qeq2(1, 5, 6)

(-3.0, -2.0)

In [23]:
qeq2(1, 1.000000001, 0.000000001)

(-1.0, -1e-09)

In [24]:
import softplus

softplus.softplus(-1)

0.31326168751822286

In [25]:
softplus.softplus(0)

0.6931471805599453

In [26]:
softplus.softplus(1000)

inf

In [27]:
softplus.softplus2(-1)

0.31326168751822286

In [28]:
softplus.softplus2(0)

0.6931471805599453

In [29]:
softplus.softplus2(1000)

1000.0

In [30]:
softplus.softplus2(-1000)

0.0

In [31]:
np.exp(2)

7.38905609893065

In [32]:
np.log(np.e)

1.0

In [33]:
np.sin(np.pi)

1.2246467991473532e-16

In [34]:
np.sqrt(3)

1.7320508075688772

In [36]:
a = np.array([2,3,5,7,8])
a[0]

2

In [37]:
a[1:3]

array([3, 5])

In [38]:
a[2:-1]

array([5, 7])

In [40]:
a[2:-2]

array([5])

In [41]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [43]:
c = np.arange(1, 3, 0.2)
c

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8])

In [44]:
a.dtype

dtype('int64')

In [45]:
c.dtype

dtype('float64')

In [47]:
d = np.array([1,2,3], dtype=np.float64)
d

array([1., 2., 3.])

In [48]:
d.dtype

dtype('float64')

In [50]:
e = np.arange(5.)
e

array([0., 1., 2., 3., 4.])

In [51]:
e.dtype

dtype('float64')

In [52]:
np.arange(5, dtype=np.float64)

array([0., 1., 2., 3., 4.])

In [53]:
# 二次元操作

In [56]:
a = np.array([[2,3,4], [5,6,7]], dtype=np.float64)
a

array([[2., 3., 4.],
       [5., 6., 7.]])

In [57]:
a[0,1]

3.0

In [58]:
a[:, 1]

array([3., 6.])

In [59]:
a[1,:]

array([5., 6., 7.])

In [60]:
a[0, 2:]

array([4.])

In [61]:
a[0, :2]

array([2., 3.])

In [63]:
a = np.arange(15.).reshape(3,5)
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [64]:
a.shape

(3, 5)

In [65]:
a.ndim

2

In [66]:
a.size

15

In [67]:
b = np.arange(4.)
b

array([0., 1., 2., 3.])

In [68]:
b.shape

(4,)

In [69]:
b.ndim

1

In [70]:
b.size

4

In [71]:
a = np.arange(16.)
c = a.reshape(4, -1)
c

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [72]:
c.ravel()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [73]:
c.reshape(-1)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [74]:
b = np.arange(4.)
b.reshape(-1, 1)

array([[0.],
       [1.],
       [2.],
       [3.]])

In [75]:
b[:, np.newaxis]

array([[0.],
       [1.],
       [2.],
       [3.]])

In [76]:
b[:, None]

array([[0.],
       [1.],
       [2.],
       [3.]])

In [77]:
b.reshape(1,-1)

array([[0., 1., 2., 3.]])

In [78]:
b[np.newaxis, :]

array([[0., 1., 2., 3.]])

In [79]:
# その他の操作

In [81]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [82]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [85]:
c = np.empty((2,5))
c

array([[1. , 1.2, 1.4, 1.6, 1.8],
       [2. , 2.2, 2.4, 2.6, 2.8]])

In [86]:
d = np.linspace(0, 1, 10)
d

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [87]:
# 行列の連結

In [92]:
a = np.arange(6).reshape(2, -1)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [93]:
b = np.arange(6, 12, 1).reshape(2, -1)
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [95]:
np.r_[a,b]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [96]:
np.c_[a,b]

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [97]:
c = np.arange(3)
c

array([0, 1, 2])

In [98]:
d = np.arange(3,6)
d

array([3, 4, 5])

In [99]:
np.r_[c,d]

array([0, 1, 2, 3, 4, 5])

In [100]:
np.c_[c,d]

array([[0, 3],
       [1, 4],
       [2, 5]])

In [101]:
np.r_[a, c] # error

ValueError: all the input arrays must have same number of dimensions

In [102]:
np.r_[a, c.reshape(1, -1)]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2]])

In [103]:
# 配列の基本計算

In [104]:
a = np.arange(5.)
a

array([0., 1., 2., 3., 4.])

In [105]:
a.sum()

10.0

In [106]:
a.mean()

2.0

In [107]:
a.max()

4.0

In [108]:
a.min()

0.0

In [109]:
b = np.arange(9.).reshape(3,3)
b

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [110]:
b.sum()

36.0

In [111]:
b.sum(axis = 0)

array([ 9., 12., 15.])

In [112]:
b.sum(axis = 1)

array([ 3., 12., 21.])

In [114]:
a = np.arange(3., 8.)
a

array([3., 4., 5., 6., 7.])

In [115]:
np.exp(a)

array([  20.08553692,   54.59815003,  148.4131591 ,  403.42879349,
       1096.63315843])

In [116]:
np.log(a)

array([1.09861229, 1.38629436, 1.60943791, 1.79175947, 1.94591015])

In [117]:
np.sqrt(a)

array([1.73205081, 2.        , 2.23606798, 2.44948974, 2.64575131])

In [119]:
b = np.arange(9.).reshape(3,3)
b

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [120]:
np.exp(b)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [121]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [122]:
a + 3

array([3, 4, 5, 6, 7])

In [123]:
a * 3

array([ 0,  3,  6,  9, 12])

In [124]:
a ** 2

array([ 0,  1,  4,  9, 16])

In [125]:
a >= 2

array([False, False,  True,  True,  True])

In [126]:
a != 3

array([ True,  True,  True, False,  True])

In [127]:
b = np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [128]:
b > 3

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [129]:
a = np.array([10, 20, 30, 40])
b = np.array([False, True, True, False])
a[b]

array([20, 30])

In [130]:
c = np.array([[3,4,5], [6,7,8]])
c

array([[3, 4, 5],
       [6, 7, 8]])

In [131]:
d = np.array([[False, False, True], [False, True, True]])
d

array([[False, False,  True],
       [False,  True,  True]])

In [132]:
c[d]

array([5, 7, 8])

In [134]:
a = np.arange(10)
a[a > 5]

array([6, 7, 8, 9])

In [135]:
a[(a >= 3) & (a < 6)]

array([3, 4, 5])

In [136]:
a[(a < 2) | (a > 7)]

array([0, 1, 8, 9])

In [137]:
a[a % 3 != 0]

array([1, 2, 4, 5, 7, 8])